services:
  backend:
    build:
      context: ./backend
    container_name: cine-magico-backend
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    environment:
      PORT: 3000
      JWT_SECRET: ${JWT_SECRET}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_DIALECT: ${DB_DIALECT}
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: cine-magico-frontend
    ports:
      - "8201:80"
    depends_on:
      - backend
    restart: unless-stopped
